### PR TITLE
Updated URL for chef

### PR DESCRIPTION
**Pull request by jjasghar**
getchef.com is 301'd to chef.io which is the forward looking domain.

Signed-off-by: JJ Asghar <jj@chef.io>

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]

**Comment by jjasghar** [comment]
I don't think my change causes this upstream issue?

```
[ERROR   ] Default group with name "jdoe" is not present
       local:
         Name: sudo - Function: pkg.latest - Result: Clean Started: - 19:20:12.161971 Duration: 2825.437 ms
       ----------
                 ID: system_user_jdoe
           Function: user.present
               Name: jdoe
             Result: False
            Comment: Default group with name "jdoe" is not present
            Started: 19:20:14.988858
           Duration: 1.889 ms
            Changes:   
       ----------
                 ID: system_user_home_/home/jdoe
           Function: file.directory
               Name: /home/jdoe
             Result: False
            Comment: One or more requisite failed: linux.system.user.system_user_jdoe
            Changes:   
       ----------
                 ID: /etc/sudoers.d/90-salt-user-jdoe
           Function: file.managed
             Result: False
            Comment: One or more requisite failed: linux.system.user.system_user_jdoe
            Changes:   
         Name: git - Function: pkg.installed - Result: Clean Started: - 19:20:14.993789 Duration: 17.608 ms
       ----------
                 ID: set_git_jdoe_param_username
           Function: git.config_set
               Name: user.name
             Result: False
            Comment: One or more requisite failed: linux.system.user.system_user_jdoe
            Changes:   
       ----------
                 ID: set_git_jdoe_param_email
           Function: git.config_set
               Name: user.email
             Result: False
            Comment: One or more requisite failed: linux.system.user.system_user_jdoe
            Changes:   
       
       Summary for local
       ------------
       Succeeded: 2
       Failed:    5
       ------------
       Total states run:     7
       Total run time:   2.845 s
```

**Comment by gtmanfred** [comment]
It does not, I have just been busy and haven't gotten around to merging this, or fixing that issue.

**Comment by jjasghar** [comment]
@gtmanfred i'll start up another PR to see if i can help out :)

**Comment by gtmanfred** [comment]
I think it may have been a bug on the linux formula, it appears to be working again.

https://travis-ci.org/saltstack/kitchen-salt/builds/371715680

**Comment by gtmanfred** [comment]
Here is where they fixed it https://github.com/salt-formulas/salt-formula-linux/commit/7f5087d5d1f645f1d179073a4678a9529eab83e8

**Comment by jjasghar** [comment]
Oh wow, cool. And I was going to use that as an excuse to learn some salt!

**Comment by gtmanfred** [comment]
Bummer :/  There are a couple things on kitchen-salt's issue tracker that
you could look at if you know ruby!  (Unfortunately I have been focused
mostly on moving the salt test suite over to using kitchen-salt to really
dive into them)

**Pull request merged**
