### PR TITLE
Fix/create usrshareformulas ootb [ WIP]

### PR DESCRIPTION
**Pull request by epcim**
review changes, rebase + squash needed.

### CODE REVIEW

**Comment by gtmanfred** [comment]
What is the point of creating this directory?  Shouldn't the packages that are installing there be providing them?

Thanks,
Daniel

**Comment by epcim** [comment]
you are right.i just found an lost commit that needs rebase and review what is whorth to merge today. gibne me me week or so.On 19 Sep 2017 18:10, Daniel Wallace <notifications@github.com> wrote:What is the point of creating this directory?  Shouldn't the packages that are installing there be providing them?
Thanks,
Daniel

**Comment by gtmanfred** [comment]
sounds good, thanks

**Comment by epcim** [comment]
all features already available - git diff shows rubbish

**Pull request closed without merging**
