### PR TITLE
Release v0.2.0

### PR DESCRIPTION
**Pull request by avanier**
This propose a release of changes made since `v0.1.0`.

I'll create another PR for a CI and a release hook that's worked well in the past for managing changelog and releases. I have to say I don't have the courage right now to backfill the changelog all the way to `v0.19.0`! 😅

### CODE REVIEW

**Comment by avanier** [comment]
Ok, preparing that other PR I'm starting to figure out how you're most likely using `rake/gem_tasks` to publish the gems and put the tags on the repo. I'm guessing I should close this PR?

**Comment by gtmanfred** [comment]
This is fine, I appreciate it.

We are in the middle of testing for our 2016.11.9 2017.7.3 and oxygen releases, so I will have a look at getting another release out soon, if you just want to leave this open.

**Comment by avanier** [comment]
Ok, after some digging, I see that you're declaring both [`gem-release`](https://github.com/svenfuchs/gem-release) and [`Bundler::GemHelper`](https://github.com/bundler/bundler/blob/master/lib/bundler/gem_helper.rb) as possible dependencies for the release.

May I make myself useful and clean that up? Do you want to have a quick look at a branch I started, it's mostly cleanup : shellcheck, Rubocop, rake tasks, ci tasks. It'd be worthwhile to ask if you even want to keep `CHANGES.md`.

Let me know how you usually release and I'll give a go at cleaning and documenting that.

[Linky](https://github.com/avanier/kitchen-salt/tree/changelog_ci) to the work in progress.

**Comment by barkingfoodog** [comment]
I saw a comment awhile back that @gtmanfred was laying groundwork for a CHANGES.md file. I'm in favor of tracking changes between releases.

**Comment by gtmanfred** [comment]
Yeah, I would like to keep the CHANGES.md

If there is a better way to keep track of that in ruby, i would be down for it.

I know that openstack has a method where each new change gets a changes file, and they get compiled into a doc before a release.

**Comment by avanier** [comment]
What's not in my branch which I was going to propose is a CI hook that checks that the first line of the `CHANGES` file is a version type, and the rake release action would auto-bump to that version type, and eat-up the contents of the changes paragraphs into the tag message. I've successfully used that before, it's pretty seamless. I would also have added a Travis test for making sure every PR has a valid entry into the `CHANGES` file.

**Comment by gtmanfred** [comment]
Does that auto release the new version when CHANGES is updated? Because I am not a super big fan of that.

**Comment by avanier** [comment]
No, the release process stays manual, but all of the data entry is automated, but the _normal_ flow would imply a release per PR.

**Comment by avanier** [comment]
Stale issue. I'll submit my PR for the CI flow by mid next-week to poke the hornet's nest.

**Pull request closed without merging**
