### PR TITLE
Adds getting the minor version to compare it to the value of salt_ver…

### PR DESCRIPTION
**Pull request by qgriffith-zz**
Fixes issue #155

### CODE REVIEW

**Comment by gtmanfred** [comment]
I would like to be able to test #155 before I merge this, can you provide an example config to replicate this?

Thanks,
Daniel

**Comment by qgriffith-zz** [comment]
```
---
driver:
  name: vagrant
  customize:
    memory: 2048

platforms:
  - name: centos-6

provisioner:
  name: salt_solo
  formula: foo
  pillars:
  state_top:
    base:
      '*':
        - foo

suites:
  - name: default
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - foo
        foo.sls:
          component: kitchen
          accessid: thisisfake
          accesskey: thisisalsofake
          env: test
      salt_version: 2016.3.7
      salt_install: yum
      require_chef: false
      collection_name: sumologic
      state_collection: true

verifier:
  name: shell
  command: testinfra -v --sudo --host="paramiko://${KITCHEN_USERNAME}@${KITCHEN_HOSTNAME}:${KITCHEN_PORT}?ssh_identity_file=${KITCHEN_SSH_KEY}" --junit-xml "junit-${KITCHEN_INSTANCE}.xml" "test/integration/${KITCHEN_SUITE}"

```

**Comment by gtmanfred** [comment]
Can you double check which version of kitchen-salt that you have?

Because this is working correctly on 0.0.28 and from github.

```
       You asked for 2016.3.7 and you have 2016.3.7 installed, sweet!
```

it was supposed to be fixed here. https://github.com/saltstack/kitchen-salt/pull/124

Thanks, Daniel

**Comment by gtmanfred** [comment]
Actually nevermind, Yeah I am not able to replicate this issue.

It is working fine here though.

```
       You asked for 2016.3.7 and you have 2016.3.7 installed, sweet!
```

Can you provide a full test setup/git repository so that I can take a closer look?

The reason I am hesitant on this is because it could break this addition https://github.com/saltstack/kitchen-salt/pull/124

@n-rodriguez can you double check this pull request for me?  I think we might need to add an if statement that only adds the final dot if it is actually in there, which would require more checks.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Actually, i just double checked my kitchen yml on the 0.0.28 tag, and it isn't working like yours isn't, can you try using the master branch of kitchen to double check your stuff?

If that fixes it, I am working on getting a new release out soon anyway.

```
       Complete!
       You asked for 2016.3.7 and you have got 2016.3 installed, dunno how to fix that, sorry!
```

```
$ git status | head -n1
HEAD detached at v0.0.28
```
Thanks,
Daniel

**Comment by qgriffith-zz** [comment]
I pulled test-kitchen gem directly from GitHub and ran my changes to
salt-ktichen and they seem to still work

gem specific_install https://github.com/test-kitchen/test-kitchen.git

**Comment by gtmanfred** [comment]
So, you used kitchen-salt without your changes from github, and it worked?

Because for me, the thing that is breaking in 0.0.28, is working on the master branch

**Comment by qgriffith-zz** [comment]
I thought you wanted me to test against test-kitchen gem from github, I can
change it to test from master kitchen-salt and not my repo and let you know

**Comment by qgriffith-zz** [comment]
Using salt-kitchen from master seems to be working for me

You asked for 2016.3.7 and you have 2016.3.7 installed, sweet!

**Comment by gtmanfred** [comment]
Awesome, I am going to close this pull request and the issue, and I will try and get a fix out there for you this week.

Thanks for helping troubleshoot.
Daniel

**Pull request closed without merging**
