### PR TITLE
Use -replace to support Powershell 2.0 on Server 2008r2

### PR DESCRIPTION
**Pull request by barkingfoodog**
Salt [officially supports Windows Server 2008r2](http://saltstack.com/wp-content/uploads/2016/08/SaltStack-Supported-Operating-Systems.pdf) which runs PowerShell 2.0. This PR makes a slight change to the `salt_command` method to support PowerShell 2.0. Credit to [this SO post](https://stackoverflow.com/questions/35641714/system-object-doesnt-contain-a-methodnamed-replace) for explaining why calling `.replace()` fails and suggesting to use `-replace` instead.

### CODE REVIEW

**Comment by barkingfoodog** [comment]
This also fixes running kitchen-salt on Windows 7.

**Comment by barkingfoodog** [comment]
@gtmanfred I got my GPG signing working. Do you want a new PR that passes the verified commit check?

**Comment by gtmanfred** [comment]
Nah, should be fine, I am off today, I will look at this tomorrow

**Comment by barkingfoodog** [comment]
@gtmanfred awesome. Enjoy the time off!

**Review by gtmanfred — APPROVED** [review]

**Comment by gtmanfred** [comment]
@barkingfoodog sorry, it looks like there is a merge conflict now, could you resolve it?

Thanks,
Daniel

**Comment by barkingfoodog** [comment]
@gtmanfred done!

**Comment by gtmanfred** [comment]
Thanks, I will get this merged once the tests pass.

Do you have an experience getting windows tests working with appveyor?  I would really like to get those setup alongside the travisci tests for kitchen-salt.

**Comment by barkingfoodog** [comment]
I agree adding Windows tests would be great! But I'm afraid I don't have any experience with appveyor or even TravisCI. We run our internal Windows and macOS tests via Jenkins + VirtualBox with images built using the [boxcutter templates](https://github.com/boxcutter). The project that inspired this enhancement runs against these OSes:
 * macOS 10.9
 * macOS 10.10
 * macOS 10.11
 * macOS 10.12
 * Windows 7 x86
 * Windows 7 x64
 * Windows 8.1 x86
 * Windows 8.1 x64
 * Windows 10 x86
 * Windows 10 x64
 * Windows Server 2008r2
 * Windows Server 2012
 * Windows Server 2016

At the moment kitchen-salt is successfully running with Salt 2017.7.2. But I'd love to see the kitchen-salt project CI pick this up.

**Pull request merged**
