### PR TITLE
fix erro when "salt_run_highstate" is not set. Run salt-call but not

### PR DESCRIPTION
**Pull request by Kurt108**
…local

I install salt via bootstrap-script and the -A option to set the salt-master. Now I want to kitchen-test a client using a "normal" salt-call

### CODE REVIEW

**Comment by simonmcc** [comment]
Would this be better controlled via a "use salt-master" flag rather than an unset salt_run_highstate?

**Comment by Kurt108** [comment]
hmmm, that is correct. And still if setting "run_highstate" is set to false there should be something instead of throwing e nil:Nil exeception ;-)

**Comment by epcim** [comment]
if setting "run_highstate" is set to false, considering whether running state that equals `suite name` is a valid use-case here ? What would you said?

**Comment by gtmanfred** [comment]
@kurt can you rebase this.

also see @epcim s comment

Thanks,
Daniel

**Comment by kurt** [comment]
@gtmanfred you got the username wrong

**Comment by gtmanfred** [comment]
woops, sorry.

@kurt--- can you rebase this?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
I am closing this for inactivity.

Would gladly reopen.

Thanks,
Daniel

**Pull request closed without merging**
