### PR TITLE
New feature - Run states at a time, allow the existence of isolated pillar

### PR DESCRIPTION
**Pull request by paulosrjr**
The idea is to enable execution of isolated states, each state with its own pillar. There are cases that pillar merging joins the same arguments in the new pillar with different values, causing errors in certain types of execution.

### CODE REVIEW

**Comment by paulosrjr** [comment]
Inside the .kitchen.yml file is necessary a blank "dummy.pillar" reference in **pillars-from-files** conf for states that not have pillar

**Comment by paulosrjr** [comment]
New .kitchen.yml example:

---

driver:
  name: ec2
  aws_ssh_key_id: "<%=ENV['AWS_SSH_KEY_ID']%>"
  region: "<%=ENV['AWS_REGION']%>"
  instance_type: t2.medium
  associate_public_ip: true
  interface: public

transport:
  ssh_key: "<%=ENV['SSH_KEY']%>"
  username: "<%=ENV['SSH_USER_NAME']%>"
  compression: true
  compression_level: 9

provisioner:
  name: salt_solo
  salt_version: 2015.8.5
  **salt_each_state: true -> or salt_run_highstate: true**
  formula: salt/base
  state_top:
    base:
      '*':
        - salt.base.product_rsyncd_server_configure
        - salt.base.product_rsyncd_client_configure
        - salt.base.product_dummy_configure

  pillars-from-files:
    product_rsyncd_server_configure.sls: salt/base/product_rsyncd_server_configure/pillar.example
    product_rsyncd_client_configure.sls: salt/base/product_rsyncd_client_configure/pillar.example
    product_dummy_configure.sls: salt/base/product_dummy_configure/pillar.example **<- Empty file**

  pillars:
    top.sls:
      base:
        '*':  
          - product_rsyncd_server_configure
          - product_rsyncd_client_configure
          - product_dummy_configure

platforms:
- name: centos-7
  driver:
    image_id: "<%=ENV['DEFAULT_IMAGE_ID']%>"
    block_device_mappings:
      - device_name: /dev/sda1
    user_data: kitchen_bootstrap_linux.template

suites:
- name: default

**Comment by paulosrjr** [comment]
Use when pillar files has same variables names, example:

**rsync server:**
uid: root
cidr: 172.16.0.0/16
_share_name: share1_   **<----**
paths: /
readonly: yes

**rsync client**
readonly: yes
_share_name: share2_   **<----**
rsync_server: 172.16.0.1
paths:
  dir1:
    name: /tmp/
    dest: /files/tmp
    args: -vzr
  dir2:
    name: /dir3/
    dest: /dir3/dir/
    args: -avz

It is useful as a unit test, and simulate isolated call by the salt-api. 
Variables at the same level suffer replacement with highstate.

**Comment by paulosrjr** [comment]
Hi @simonmcc, this PR is plausible?

Tks

**Comment by epcim** [comment]
I do a pillar_from_file on each individual suite? Sure I may reference multiple files and than will suffer. Honestly to merge it must be compatible .kitchen.yml from previous releases which I guess will not as you set `salt_run_highstate: false`.

**Comment by cmarzullo** [comment]
I'm with @epcim on this one. Is this a new problem? I regularly have different pillar for different test suites.

**Comment by jbussdieker** [comment]
There is a bug that requires at least a dummy pillar configured in the `pillar` config otherwise it will crash trying to `unsymbolize` a nil object. That should be fixed in the next release.

I agree with the spirit of your approach just not the implementation. The next major release should provide more flexibility to how salt is called including the ability to run something like `salt-call state.apply STATE_NAME` which could reference a different state per test suite. I believe those features would cover your use case while still maintaining flexibility for others.

**Pull request closed without merging**
