### PR TITLE
Salt solo default config update

### LINKED ISSUE #32: salt_apt_repo not working
Having an issue trying to get kitchen-salt to use newer packages from saltstack. I need to test 2015.8 on debian. That version doesn't appear available in apt. I can point to http://debian.saltstack.com/debian/dists/jessie-saltstack/ manually in a sources file, but this URL won't work int salt_apt_repo.

Looking at the code at https://github.com/cmarzullo/kitchen-salt/blob/master/lib/kitchen/provisioner/salt_solo.rb#L104

It seems a URL path is hard coded into the install script that gets copied over. Perhaps the repo structure has changed a bunch.

I'll see if I can get something made up as a PR.

### PR DESCRIPTION
**Pull request by ek9**
- Update `salt_bootstrap_url` to use `https` protocol by default
- Update `salt_apt_repo` and `salt_apt_repo_key` defaults to be working examples (I've defaulted to Ubuntu as this seems to make most sense considering Ubuntu is mentioned in the README). Let me know if I need adjusting it.

This would fix #32

### CODE REVIEW

**Comment by simonmcc** [comment]
If we merge this, the default_0162 examples in the docs will break, as we're no longer making that version available - can you re-write that default_0162 example so that it uses an alternative version available from salt directly?  (0.16.2 is very old now!!)

**Comment by ek9** [comment]
Will sort that out in a moment.

**Comment by ek9** [comment]
@simonmcc could you link me which files you mean by `0612` example? I've looked in the `docs` folder but I am unable to find it

**Comment by simonmcc** [comment]
@ek9 the first YAML example in provisioner_options.md has 

```
  - name: default_0162
    provisioner:
      salt_version: 0.16.2
      salt_install: apt
```

Maybe we should just update the 0162 examples to be something more recent like using the 2016.3 release from http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2016.3 ?

**Comment by ek9** [comment]
I've checked and `salt_version` is set to `latest` by default, so I have updated the documentation accordingly.

Regarding the versions, I've updated the example to use `2016.11.2` as that's the version that `salt_apk_repo_key` and `salt_apk_repo` are set default to. Let me know if you want me to switch it to `2016.3`

**Review by simonmcc — APPROVED** [review]

**Pull request merged**
