### PR TITLE
Itp 991 custom minion

### PR DESCRIPTION
**Pull request by luddite0**

### CODE REVIEW

**Comment by gtmanfred** [comment]
@bellaweo can you rebase this PR?
Thanks,
Daniel

**Comment by gtmanfred** [comment]
@bellaweo it seems like #93 meets the need here, does this change work for you?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
I am closing this for inactivity.

Would gladly reopen.

Thanks,
Daniel

**Comment by luddite0** [comment]
sorry for the late reply. it does appear #93 takes care of this. although for our purposes, we do need to run a saltutil.sync_all before the highstate. i can open a new pr with that addition.

**Comment by gtmanfred** [comment]
That would be awesome!

Thanks!
Daniel

**Pull request closed without merging**
