### PR TITLE
Add :pillars_from_directories option.

### PR DESCRIPTION
**Pull request by n-rodriguez**
This option takes a list of hash:
- source: './test/fixtures'
  dest: '/srv/saltconfig'

and allows to copy recursively the content of the source dir to the dest.

### CODE REVIEW

**Comment by gtmanfred** [comment]
Is there a reason to have source and dest?  Why not just copy them into /tmp/kitchen/srv/pillar?

Thanks,
Daniel

**Comment by n-rodriguez** [comment]
> Is there a reason to have source and dest? Why not just copy them into /tmp/kitchen/srv/pillar?
> 
> Thanks,
> Daniel

Hi! Actually the dest directory is implicitly copied under `/tmp/kitchen`. The dest dir is here to tell where to copy the directory under `/tmp/kitchen`. I would let it "open" to not add useless constraints on dest dir. The implementation largely depends on users. (for example : in our case the dest dir will never be /srv/pillar).

**Comment by gtmanfred** [comment]
Ok, i am ok with this, but I would like it to default /srv/pillar, and not have to define a destination by default.

```
pillars_from_directories:
  - test/pillars
```

or 
```
pillars_from_directories:
  - source: test/pillars
    dest: /srv/saltconfig/pillars
```

Can you do that? 

Thanks,
Daniel

**Comment by gtmanfred** [comment]
perfect, thanks!

I am going to get this one merged, and make 0.0.29

**Comment by n-rodriguez** [comment]
Great! Thank you!

**Pull request merged**
