### PR TITLE
Test and merge upstream PRs

### PR DESCRIPTION
**Pull request by epcim**
Hi, If anybody is interested I merged most of the interesting PRs (after testing, with minor reasonable fixups) on top of my #56 (CI on Travis). Current status: https://travis-ci.org/epcim/kitchen-salt/branches

@simonmcc I would kindly ask you for comments. Considering merge + release new gem version. 

There is definitively a great potential to move the project forward (dependencies, kind of chef-zero for multi node testing, better handling of test suites (like if dirs/files are missing)) however these may bring more changes and it would be much better to have most PRs merged. Thanks.

### CODE REVIEW

**Comment by cmarzullo** [comment]
👍 

thanks for picking this up!

**Comment by jbussdieker** [comment]
Awesome thanks!

**Comment by simonmcc** [comment]
This is brilliant, thank you for putting the effort in to this!

**Comment by simonmcc** [comment]
@epcim did you happen to track the issues/PRs that can be closed with this?

**Comment by jschectman-vs** [comment]
@epcim @simonmcc commit 6217caba720174aa25d182a4636cb0dfc871bff8 - seems to have broken copying my top.sls in the pre-built collection case - I get an empty top.sls

**Pull request merged**
