### PR TITLE
Update script, to add then, fixes #107

### LINKED ISSUE #107: if statement issue after update to 0.0.25 in salt_solo
Hi all,

All my CIs are now failing after the gem was updated to 0.0.25, and I get the following error with running kitchen

```
kitchen converge default-centos-7
-----> Starting Kitchen (v1.16.0)
-----> Converging <default-centos-7>...
       Preparing files for transfer
       Preparing salt-minion
       Preparing pillars into /srv/pillar
       Preparing formula: collectd from /Users/arif/gitRepos/salt-formula/salt-formula-collectd
       Preparing formula: repos from srv/salt
       Preparing state_top
       Preparing scripts into /etc/salt/scripts
       You asked for latest and you have 2016.11.5 installed, sweet!
-----> Trying to install ruby(-dev) using assets.sh from kitchen-salt
       downloading https://raw.githubusercontent.com/saltstack/kitchen-salt/master/assets/install.sh
         to file /tmp/install.sh
       trying wget...
       Installing the ruby things
       installing with yum...
       Loaded plugins: fastestmirror, ovl
       Loading mirror speeds from cached hostfile
        * base: mirror.vorboss.net
        * epel: mirror.bytemark.co.uk
        * extras: mirror.vorboss.net
        * updates: mirror.econdc.com
       Package ruby-2.0.0.648-29.el7.x86_64 already installed and latest version
       Package ruby-devel-2.0.0.648-29.el7.x86_64 already installed and latest version
       Nothing to do
       ln: failed to create symbolic link '/opt/chef/embedded/bin/gem': File exists
       ln: failed to create symbolic link '/opt/chef/embedded/bin/ruby': File exists
       sh: -c: line 190: syntax error near unexpected token `fi'
       sh: -c: line 190: `                fi;'
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-centos-7>.  Please see .kitchen/logs/default-centos-7.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

### PR DESCRIPTION
**Pull request by arif-ali**

### CODE REVIEW

**Comment by arif-ali** [comment]
Can we put this through ASAP, as all of my CI are now failing, unless I sticky the version  to the previous version

Thanks

**Comment by thunder-spb** [comment]
+1 we need this ASAP!

**Comment by arif-ali** [comment]
@gtmanfred, hi, as one of the committers, could you have a look please?

**Comment by arif-ali** [comment]
So, even, if we sticky to the older version, I still get the same problem.

This is now a regression, and a major bug

**Pull request merged**
