### PR TITLE
make chef install for busser optionally

### PR DESCRIPTION
**Pull request by neillturner**
added option to make chef install optionally as it is is in kitchen-puppet and kitchen-ansible.

### CODE REVIEW

**Comment by epcim** [comment]
Working on merge of multiple PRs. Considering rename the option to `require_chef`. Btw. there is an similar (but not implemented) option on kitchen docker: https://github.com/test-kitchen/kitchen-docker/search?utf8=%E2%9C%93&q=require_chef_omnibus.

In both cases, `require_chef` better describes the result.

**Comment by cmarzullo** [comment]
I support the require_chef flag!

**Comment by ssplatt** [comment]
i support the toggle too, as long as busser still works at the end of the day.

**Comment by scub** [comment]
👍

**Pull request merged**
