### PR TITLE
Added vendor_path config to allow specifying dependencies

### PR DESCRIPTION
**Pull request by milosgajdos**
This allows you to specify vendor_path which contains dependant formulas.

This also adds follow-symlink-during-copy.

### CODE REVIEW

**Comment by simonmcc** [comment]
@milosgajdos83 are you using :vendor_path anywhere?  I've been away from salt for a while & just spotted that it breaks if we don't check that the vendor_path actually exists

**Comment by ashb** [comment]
@simonmcc Here's a public example of it: https://github.com/ministryofjustice/jenkins-formula/blob/master/.kitchen.yml#L5

**Comment by simonmcc** [comment]
OK, cool, I have a fix that gracefully handles vendor_path not existing (or just not being set, which is what was tripping me up!) - this is a further reminder that I need to get some CI setup on this :(

**Comment by milosgajdos** [comment]
Happy to help out with setting up something like Travis.

**Pull request merged**
