### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by barkingfoodog**
Copying windows support from #41. Added basic tests on `install_command`, `init_command`, and `run_command`. Switched to using chef-client since serverspec busser looks for C:\opscode\chef\embedded\bin\ruby.exe. In `create_sandbox` replace $env:TEMP with C:\tmp since Salt can't evaluate environment variables in the minion file.

The beaver-formula project will converge but with errors. This appear to be because the beaver states are unix-focused. Also, `run_command` does some fancy grepping for false-negatives which I didn't port over. If we can get some examples of these against which a Windows-friendly search can be developed, I'll be happy to take a crack at it.

 A big thanks to @PatOShea for his initial work on Windows support.

### CODE REVIEW

**Comment by epcim** [comment]
Nice, can you please provide an salt formula for windows OS with .kitchen.yml in it, so we may test it first. Thanks

**Comment by barkingfoodog** [comment]
I'll be happy to put up an example. I should have that together before the weekend is out.

**Comment by barkingfoodog** [comment]
I put together a [basic example](https://github.com/barkingfoodog/kitchen-salt-win-sample). Let me know if you need any help getting it up an running.

**Comment by gtmanfred** [comment]
@barkingfoodog can you rebase this PR?

Thanks,
Daniel

**Comment by barkingfoodog** [comment]
Yup. Let me work on this and I'll push a new set of commits.

**Comment by gtmanfred** [comment]
Awesome, thanks!

**Comment by gtmanfred** [comment]
closing based on discussion in #74

**Pull request closed without merging**
