### PR TITLE
Add a `nox` verfier

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by gtmanfred** [comment]
@s0undt3ch is this good to go now?

**Comment by s0undt3ch** [comment]
Yes, for now it is.
I have some PowerShell fixing to do but it doesn't prevent it from working.
Thanks!

**Comment by s0undt3ch** [comment]
Work is complete now.

**Comment by gtmanfred** [comment]
@s0undt3ch can you take a look at the failing tests?

**Comment by s0undt3ch** [comment]
```
       ----------
                 ID: git_packages
           Function: pkg.installed
               Name: u'git'
             Result: False
            Comment: Error occurred installing package(s). Additional info follows:
              
              errors:
                  - Loaded plugins: fastestmirror, ovl
                    Loading mirror speeds from cached hostfile
                     * base: mirrors.advancedhosters.com
                     * epel: mirror.steadfastnet.com
                     * extras: mirror.grid.uchicago.edu
                     * updates: mirrors.advancedhosters.com
                    No package u'git' available.
                    Error: Nothing to do
```
I fail to see why this PR would trigger the git package not being found....

I'll have a better look tomorrow.

**Comment by gtmanfred** [comment]
I think it could be a bug in 2019.2, that we may need to pin tests to 2018.3, and push the issue upstream.

**Comment by gtmanfred** [comment]
Infact, i am pretty sure it is that.

**Comment by gtmanfred** [comment]
Infact, i know it is that, we need to add `|tojson` to the formula, for testing on 2019.2

**Comment by gtmanfred** [comment]
https://docs.saltstack.com/en/develop/topics/releases/fluorine.html#non-backward-compatible-change-to-yaml-renderer

**Comment by gtmanfred** [comment]
This should fix the issue. https://github.com/saltstack/kitchen-salt/pull/284

**Comment by gtmanfred** [comment]
@s0undt3ch it looks like python-systemd has been added back to the salt repos, so hopefully i can get the test suite fixed today and get this in :+1: with a release.

**Comment by s0undt3ch** [comment]
Thanks!
Sorry I didn't reply sooner but nox  and golden images have taken all of my time.

**Comment by gtmanfred** [comment]
@s0undt3ch no worries, looks like test have passed, are you ready with this?

**Review by gtmanfred — APPROVED** [review]

**Comment by s0undt3ch** [comment]
This is now good to go.

**Comment by s0undt3ch** [comment]
Thank You!

**Pull request merged**
